version: "3.9"
services:
  test:
    build: .
    ports:
      - "8000:8080"
    environment:
      KAFKA_BROKERS: test
      KAFKA_CA_PATH: test
      KAFKA_CERTIFICATE_PATH: test
      KAFKA_PRIVATE_KEY_PATH: test
      KAFKA_SCHEMA_REGISTRY: test
