apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pam-statistikk-data-consumer-alert
  namespace: teampam
  labels:
    team: teampam
spec:
  groups:
  - name: pam-statistikk-data-consumer-alert
    rules:
    - alert: ContainerKilled
      expr: time() - container_last_seen{container="pam-statistikk-data-consumer"} > 60
      for: 5m
      annotations:
        consequence: Ingen containere for applikasjonen pam-statistikk-data-consumer finnes, kan ødelegge for statistikken!
        action: "logger på https://logs.adeo.no -> søk etter `application: \"pam-statistikk-data-consumer\"` "
        message: "Må gjøres ASAP! Kan ødelegge for statistikk om denne jobben ikke kjører minst en gang daglig."
        summary: "Container killed (instance {{ $labels.instance }})"
      labels:
        namespace: teampam
        severity: warning

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pam-statistikk-nais-job-alert
  namespace: teampam
  labels:
    team: teampam
spec:
  groups:
  - name: pam-statistikk-nais-job-alert
    rules:
    - alert: pam-statistikk-nais-job Naisjob feiler
      expr: kube_job_status_failed{job_name="pam-statistikk-nais-job"} > 0
      for: 2m
      annotations:
        summary: "Denne jobben kjører kun en gang om dagen og er viktig for statistikk"
        consequence: Naisjob feiler, kan gi feil i statistikken
        action: |
          ´kubectl describe pod pam-statistikk-nais-job -n teampam´
          For pod laget av job, kjør ´kubectl logs <podname>´
          Se logger på https://logs.adeo.no -> søk etter `application: "pam-statistikk-nais-job"`
        message: "Må gjøres ASAP! Kan ødelegge for statistikk om denne jobben ikke kjører minst en gang daglig."
      labels:
        namespace: teampam
        severity: danger
    - alert: pam-statistikk-nais-job Naisjob Kjørte ikke
      expr: time() - max(kube_job_status_completion_time{job_name=~"pam-statistikk-nais-job></naisjob-navn>.+"}) > 90000
      for: 1m
      annotations:
        summary: Naisjob pam-statistikk-nais-job har mulig ikke kjørt i riktig tidsrom!
        consequence: Naisjob kjørte ikke, kan gi feil i statistikken
        action: "Se logger på https://logs.adeo.no -> søk etter `pod:pam-statistikk-nais-job> AND namespace:teampam`"
      labels:
        namespace: teampam
        severity: warning

