apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: pam-statistikk-nais-job
  namespace: teampam
  labels:
    "team": teampam
spec:
  image: {{image}}
  envFrom:
    - secret: pam-statistikk-job
  env:
    - name: BUCKET
      value: {{ bucket_name }}
  schedule: "0 3 * * *"
  backoffLimit: 5
  resources:
    limits:
      cpu: "2000m"
      memory: "8Gi"
  gcp:
    permissions:
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
      role: roles/cloudsql.client
    buckets:
      - name: {{ bucket_name }}
        premission: READ
  accessPolicy:
    outbound:
      external:
        - host: 34.88.234.250
          port: 3307
