apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-statistikk-data-consumer
  namespace: teampam
  labels:
    "team": teampam
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: pam-statistikk-db
            envVarPrefix: DB
            users:
              - name: statistikk-read-user

---

apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: "pam-statistikk-data-consumer-alert"
  namespace: "teampam"
  labels:
    "team": "teampam"
    "start.nais.io/created-by": "me"
spec:
  receivers:
    slack:
      channel: "arbeidsplassen-data"
      prependText: "<!here> | "
      send_resolved: true
      username: "PAM Alert-o-Bot"
  alerts:
    - alert: "ContainerKilled"
      expr: "time() - container_last_seen{container=\"pam-statistikk-data-consumer\"} > 60"
      for: "5m"
      summary: "Container killed (instance {{ $labels.instance }})"
      description: "Ingen kontainere ble funnet for applikasjonen pam-statistikk-data-consumer"
      documentation: "https://github.com/navikt/pam-statistikk-data-consumer"
      action: "logger på https://logs.adeo.no -> søk etter `application: \"pam-statistikk-data-consumer\"` "
      sla: "Må gjøres ASAP! Kan ødelegge for statistikk om denne jobben ikke kjører minst en gang daglig."
      severity: "warning"

