apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: pam-statistikk-nais-job
  namespace: teampam
  labels:
    "team": teampam
spec:
  image: {{image}}
  envFrom:
    - secret: pam-statistikk-job
  schedule: "30 10 * * *"
  backoffLimit: 5
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
  gcp:
    permissions:
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
      role: roles/cloudsql.client
    buckets:
      - name: pam-statistikk
        premission: READ

---

apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: "pam-statistikk-nais-job-alert"
  namespace: "teampam"
  labels:
    "team": "teampam"
    "start.nais.io/created-by": "me"
spec:
  receivers:
    slack:
      channel: "arbeidsplassen-data"
      prependText: "<!here> | "
      send_resolved: true
      username: "PAM Alert-o-Bot"
  alerts:
  - alert: "pam-statistikk-nais-job Naisjob feiler"
    description: "Denne jobben kjører kun en gang om dagen og er viktig for statistikk"
    expr: "kube_job_status_failed{job_name=\"pam-statistikk-nais-job\"} >= 1"
    for: "2m"
    action: "´kubectl describe pod pam-statistikk-nais-job -n teampam´ \
      \ For pod laget av job, kjør ´kubectl logs <podname>´
      \ Se logger på https://logs.adeo.no -> søk etter `application: \"pam-statistikk-nais-job\"` "
    documentation: "https://github.com/navikt/pam-statistikk-data-consumer"
    sla: "Må gjøres ASAP! Kan ødelegge for statistikk om denne jobben ikke kjører minst en gang daglig."
    severity: "danger"

  - alert: "pam-statistikk-nais-job Naisjob mangler!"
    description: "En viktig nais job er fjernet \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}."
    expr: "absent(up{job="pam-statistikk-nais-job"})"
    for: "2m"
    action:
      "Kjør den opp igjen enten med github workflows, eller se etter feil i \
      \ logger på https://logs.adeo.no -> søk etter `application: \"pam-statistikk-nais-job\"` "
    documentation: "https://github.com/navikt/pam-statistikk-data-consumer"
    sla: "Må gjøres ASAP! Kan ødelegge for statistikk om denne jobben ikke kjører minst en gang daglig."
    severity: "danger"
