apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-statistikk-data-consumer
  namespace: teampam
  labels:
    "team": teampam
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: pam-statistikk-db
            envVarPrefix: DB
            users:
              - name: statistikk-read-user

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pam-statistikk-data-consumer-alert
  namespace: teampam
  labels:
    team: teampam
spec:
  groups:
  - name: pam-statistikk-data-consumer-alert
    rules:
    - alert: ContainerKilled
      expr: 'time() - container_last_seen{container=\"pam-statistikk-data-consumer\"} > 60'
      for: 5m
      annotations:
        consequence: Ingen containere for applikasjonen pam-statistikk-data-consumer finnes, kan ødelegge for statistikken!
        action: "logger på https://logs.adeo.no -> søk etter `application: \"pam-statistikk-data-consumer\"` "
        message: "Må gjøres ASAP! Kan ødelegge for statistikk om denne jobben ikke kjører minst en gang daglig."
        summary: "Container killed (instance {{ $labels.instance }})"
      labels:
        namespace: teampam
        severity: warning