"kafka_pool": "nav-prod"
"bucket_name": "pam-statistikk-prod"
"cloudsql_db_tier": "db-custom-1-3840"
"consumer_group_id": "pam-statistikk-data-consumer-v1"
"cv_endret_intern_topic": "teampam.cv-endret-intern-v3"
