apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pam-statistikk-nais-job-db
  namespace: teampam
spec:
  egress:
    - to:
      - ipBlock:
          gcidr: 34.88.234.250/32
  podSelector:
    matchLabels:
      db: pam-statistikk-nais-job
  policyTypes:
    - Egress
