name: "Build and deploy statistikk-data-consumer"
on:
  push:
    branches:
    - "main"
    paths:
      - 'app/**'
      - '.nais/nais-application.yaml'
      - '.github/workflows/consumer.yaml'

env:
  "CONSUMER_IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build consumer-application"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "setup python"
      uses: "actions/setup-python@v2"
      with:
        "python-version": "3.x"
    - name: "Login to GitHub Docker Registry"
      uses: "docker/login-action@v1"
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"
    - name: "Build and push the Docker image"
      run: "docker build . -f app/Dockerfile --pull --tag ${CONSUMER_IMAGE} && docker push ${CONSUMER_IMAGE}"
  "deployAppToDev":
    name: "Deploy consumer-application to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        CLUSTER: "dev-gcp"
        RESOURCE: ".nais/nais-application.yaml"
        VARS: ".nais/dev.yaml"
        VAR: image=${{ env.CONSUMER_IMAGE }}
#  "deployAppToProd":
#    name: "Deploy consumer-application to prod"
#    needs: ["build", "deployAppToDev"]
#    runs-on: "ubuntu-latest"
#    steps:
#    - uses: "actions/checkout@v3"
#    - name: "Deploy to PROD"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        CLUSTER: "prod-gcp"
#        RESOURCE: ".nais/nais-application.yaml"
#        VARS: ".nais/prod.yaml"
#        VAR: image=${{ env.CONSUMER_IMAGE }}
