name: "Deploy statistikk-data-consumer til prod"
on:
  release:
    types: [published]

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v6
    with:
      NAIS_RESOURCE: .nais/nais-application.yaml
      NAIS_VARS: .nais/prod.yaml
