name: "Build and deploy statistikk-data nais-jobb :)"
on:
  push:
    branches:
    - "main"
    paths:
      - 'job/**'
      - '.nais/nais-job.yaml'
      - '.github/workflows/naisjob.yaml'
jobs:
  build_and_deploy:
    permissions:
      contents: read
      id-token: write
      actions: read
    name: Build and deploy job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        "python-version": "3.x"
    - uses: nais/docker-build-push@v0
      id: docker-push
      with:
        team: teampam
        push_image: true
        dockerfile: job/Dockerfile
    - name: "Deploy to DEV"
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp
        RESOURCE: ".nais/nais-job.yaml,.nais/dev-db.yaml"
        VARS: ".nais/dev.yaml"
        IMAGE: ${{ steps.docker-push.outputs.image }}
        TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}
    - name: "Deploy to PROD"
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp
        RESOURCE: ".nais/nais-job.yaml,.nais/prod-db.yaml"
        VARS: ".nais/prod.yaml"
        IMAGE: ${{ steps.docker-push.outputs.image }}
        TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}
